services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    restart: unless-stopped
    command: bash -c "rm -f /opt/oracle/diag/tnslsnr/*/listener/alert/log.xml && /bin/sh /opt/oracle/scripts/startup/startup.sh"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo select 1 from dual | sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XEPDB1 | grep -q 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  flyway:
    image: flyway/flyway:latest
    depends_on:
      oracle:
        condition: service_healthy
    command: -url=jdbc:oracle:thin:@oracle:1522/XEPDB1 -user=system -password=${ORACLE_PASSWORD} -locations=filesystem:/flyway/common,filesystem:/flyway/sql -baselineOnMigrate=true migrate
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - ./backend/src/main/resources/db/migration/oracle:/flyway/sql
      - ./backend/src/main/resources/db/migration/common:/flyway/common
