version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    healthcheck:
      test: ["CMD", "bash", "-c", "echo select 1 from dual | sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XEPDB1 | grep -q 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  flyway:
    image: flyway/flyway:latest
    depends_on:
      oracle:
        condition: service_healthy
    command: -url=jdbc:oracle:thin:@oracle:1521/XEPDB1 -user=system -password=${ORACLE_PASSWORD} -locations=filesystem:/flyway/common,filesystem:/flyway/sql migrate
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - ./backend/src/main/resources/db/migration/oracle:/flyway/sql
      - ./backend/src/main/resources/db/migration/common:/flyway/common
