FROM maven:3.8.6-openjdk-18

RUN apt-get update && apt-get install -y netcat curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

# Wait for Oracle DB to be ready
CMD /bin/sh -c "\
  until nc -z oracle 1521; do \
    echo 'Waiting for Oracle DB...'; \
    sleep 5; \
  done; \
  mvn -B -ntp flyway:migrate -Pmedium-test"
