-- Create CORE schema
CREATE SCHEMA IF NOT EXISTS CORE;

-- Create TAX_BRACKET table to store tax bracket configurations
CREATE TABLE CORE.TAX_BRACKET (
    ID VARCHAR(50) PRIMARY KEY,
    BRACKET_VALUE VARCHAR(50) NOT NULL UNIQUE,
    LABEL VARCHAR(200) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_TAX_BRACKET_VALUE CHECK (LENGTH(BRACKET_VALUE) > 0)
);

-- Create TAX_BRACKET_DETAIL table to store progressive tax rates for each bracket
CREATE TABLE CORE.TAX_BRACKET_DETAIL (
    ID VARCHAR(50) PRIMARY KEY,
    BRACKET_ID VARCHAR(50) NOT NULL,
    MIN_INCOME BIGINT NOT NULL,
    MAX_INCOME BIGINT,
    TAX_RATE DOUBLE NOT NULL,
    DEDUCTION BIGINT NOT NULL DEFAULT 0,
    BRACKET_SEQ INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BRACKET_DETAIL_BRACKET FOREIGN KEY (BRACKET_ID) REFERENCES CORE.TAX_BRACKET(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TAX_RATE CHECK (TAX_RATE >= 0 AND TAX_RATE <= 100),
    CONSTRAINT CHK_MIN_INCOME CHECK (MIN_INCOME >= 0),
    CONSTRAINT CHK_INCOME_RANGE CHECK (MAX_INCOME IS NULL OR MAX_INCOME > MIN_INCOME)
);

-- Create index for better query performance
CREATE INDEX CORE.IDX_TAX_BRACKET_DETAIL_BRACKET_ID ON CORE.TAX_BRACKET_DETAIL(BRACKET_ID);
CREATE INDEX CORE.IDX_TAX_BRACKET_EFFECTIVE_DATE ON CORE.TAX_BRACKET(EFFECTIVE_DATE);

-- Create DEDUCTION_BRACKET table for deduction configurations
CREATE TABLE CORE.DEDUCTION_BRACKET (
    ID VARCHAR(50) PRIMARY KEY,
    BRACKET_VALUE VARCHAR(50) NOT NULL UNIQUE,
    LABEL VARCHAR(200) NOT NULL,
    PERSONAL_DEDUCTION BIGINT NOT NULL,
    DEPENDENT_DEDUCTION BIGINT NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_DEDUCTION_VALUE CHECK (LENGTH(BRACKET_VALUE) > 0)
);

-- Create WAGE_ZONE table for wage zone configurations
CREATE TABLE CORE.WAGE_ZONE (
    ID VARCHAR(50) PRIMARY KEY,
    ZONE_VALUE VARCHAR(50) NOT NULL UNIQUE,
    LABEL VARCHAR(200) NOT NULL,
    MINIMUM_WAGE BIGINT NOT NULL,
    BHTN_INSURANCE_CAP BIGINT NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_WAGE_ZONE_VALUE CHECK (LENGTH(ZONE_VALUE) > 0),
    CONSTRAINT CHK_WAGE_ZONE_MIN CHECK (MINIMUM_WAGE >= 0),
    CONSTRAINT CHK_WAGE_ZONE_CEILING CHECK (BHTN_INSURANCE_CAP > MINIMUM_WAGE)
);
