apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: money-keeper
  namespace: money-keeper
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: money-keeper.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: money-keeper-backend        # <-- ĐÚNG tên Service backend của bạn
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: money-keeper-frontend-service
            port:
              number: 80
