apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: money-keeper-frontend-ingress
  namespace: money-keeper
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: money-keeper.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: money-keeper-frontend-service
            port:
              number: 80
