DECLARE
  user_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO user_count FROM dba_users WHERE username = 'CORE';
  IF user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CORE IDENTIFIED BY core_password';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO CORE';
    EXECUTE IMMEDIATE 'ALTER USER CORE DEFAULT TABLESPACE USERS';
    EXECUTE IMMEDIATE 'ALTER USER CORE TEMPORARY TABLESPACE TEMP';
  END IF;
END;
/
