CREATE TABLE CORE.TAX_BRACKET (
    ID VARCHAR2(50) PRIMARY KEY,
    BRACKET_VALUE VARCHAR2(50) NOT NULL UNIQUE,
    LABEL VARCHAR2(200) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_TAX_BRACKET_VALUE CHECK (LENGTH(BRACKET_VALUE) > 0)
);

CREATE TABLE CORE.TAX_BRACKET_DETAIL (
    ID VARCHAR2(50) PRIMARY KEY,
    BRACKET_ID VARCHAR2(50) NOT NULL REFERENCES CORE.TAX_BRACKET(ID),
    MIN_INCOME NUMBER(15,0) NOT NULL,
    MAX_INCOME NUMBER(15,0),
    TAX_RATE NUMBER(5,2) NOT NULL,
    DEDUCTION NUMBER(15,0) NOT NULL DEFAULT 0,
    BRACKET_ORDER NUMBER(2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE CORE.TAX_BRACKET_DETAIL 
ADD CONSTRAINT CHK_MIN_INCOME CHECK (MIN_INCOME >= 0);

ALTER TABLE CORE.TAX_BRACKET_DETAIL 
ADD CONSTRAINT CHK_TAX_RATE CHECK (TAX_RATE >= 0 AND TAX_RATE <= 100);

ALTER TABLE CORE.TAX_BRACKET_DETAIL 
ADD CONSTRAINT CHK_INCOME_RANGE CHECK (MAX_INCOME IS NULL OR MAX_INCOME > MIN_INCOME);

CREATE INDEX IDX_TAX_BRACKET_DETAIL_BRACKET_ID 
ON CORE.TAX_BRACKET_DETAIL(BRACKET_ID);

CREATE INDEX IDX_TAX_BRACKET_EFFECTIVE_DATE 
ON CORE.TAX_BRACKET(EFFECTIVE_DATE);

CREATE TABLE CORE.DEDUCTION_BRACKET (
    ID VARCHAR2(50) PRIMARY KEY,
    BRACKET_VALUE VARCHAR2(50) NOT NULL UNIQUE,
    LABEL VARCHAR2(200) NOT NULL,
    PERSONAL_DEDUCTION NUMBER(15,0) NOT NULL,
    DEPENDENT_DEDUCTION NUMBER(15,0) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_DEDUCTION_VALUE CHECK (LENGTH(BRACKET_VALUE) > 0)
);

CREATE TABLE CORE.WAGE_ZONE (
    ID VARCHAR2(50) PRIMARY KEY,
    ZONE_VALUE VARCHAR2(50) NOT NULL UNIQUE,
    LABEL VARCHAR2(200) NOT NULL,
    MINIMUM_WAGE NUMBER(15,0) NOT NULL,
    BHTN_INSURANCE_CAP NUMBER(15,0) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_WAGE_ZONE_VALUE CHECK (LENGTH(ZONE_VALUE) > 0),
    CONSTRAINT CHK_WAGE_ZONE_MIN CHECK (MINIMUM_WAGE >= 0),
    CONSTRAINT CHK_WAGE_ZONE_CEILING CHECK (BHTN_INSURANCE_CAP > MINIMUM_WAGE)
);
