-- Oracle-compatible initial schema

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    icon VARCHAR2(255),
    type VARCHAR2(10) CHECK (type IN ('EXPENSE', 'INCOME')),
    parent_id NUMBER,
    CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);
