-- Oracle-compatible migration script to create currency table

CREATE TABLE CORE.currency (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(10) NOT NULL UNIQUE,
    name VARCHAR2(100) NOT NULL,
    symbol VARCHAR2(10),
    flag VARCHAR2(255)
);
