-- Oracle-compatible migration script to create currency table

CREATE TABLE currency (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(10) NOT NULL UNIQUE,
    name VARCHAR2(100) NOT NULL
);

INSERT INTO currency (code, name) VALUES
('USD', 'US Dollar');
INSERT INTO currency (code, name) VALUES
('EUR', 'Euro');
INSERT INTO currency (code, name) VALUES
('VND', 'Vietnamese Dong');
INSERT INTO currency (code, name) VALUES
('JPY', 'Japanese Yen');
INSERT INTO currency (code, name) VALUES
('GBP', 'British Pound');
INSERT INTO currency (code, name) VALUES
('AUD', 'Australian Dollar');
