-- Oracle-compatible migration script to create currency table

CREATE TABLE currency (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(10) NOT NULL UNIQUE,
    name VARCHAR2(100) NOT NULL,
    symbol VARCHAR2(10),
    flag VARCHAR2(255)
);

INSERT INTO currency (code, name, symbol, flag) VALUES
('USD', 'US Dollar', '$', 'https://flagcdn.com/w40/us.png');
INSERT INTO currency (code, name, symbol, flag) VALUES
('EUR', 'Euro', '€', 'https://flagcdn.com/w40/eu.png');
INSERT INTO currency (code, name, symbol, flag) VALUES
('VND', 'Vietnamese Dong', '₫', 'https://flagcdn.com/w40/vn.png');
INSERT INTO currency (code, name, symbol, flag) VALUES
('JPY', 'Japanese Yen', '¥', 'https://flagcdn.com/w40/jp.png');
INSERT INTO currency (code, name, symbol, flag) VALUES
('GBP', 'British Pound', '£', 'https://flagcdn.com/w40/gb.png');
INSERT INTO currency (code, name, symbol, flag) VALUES
('AUD', 'Australian Dollar', '$', 'https://flagcdn.com/w40/au.png');
