server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
    app:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
      mode: full

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    root: INFO
