{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: money-keeper-frontend
  namespace: {{ include "money-keeper.namespace" . }}
  labels:
    {{- include "money-keeper.labels" . | nindent 4 }}
    {{- include "money-keeper.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
