-- Oracle-compatible migration script to create account table with trigger

CREATE TABLE CORE.account (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR2(255) NOT NULL,
    init_balance NUMBER(19, 4) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    currency VARCHAR2(10) NOT NULL,
    description VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_account_updated_at
BEFORE UPDATE ON CORE.account
FOR EACH ROW
BEGIN
    :new.updated_at := CURRENT_TIMESTAMP;
END;
/ 

CREATE INDEX idx_account_type ON CORE.account(type);
CREATE INDEX idx_account_currency ON CORE.account(currency);
