name: E2E Tests and Report

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: e2e
        run: npm ci

      - name: Run E2E tests
        working-directory: e2e
        run: npm run test
        
      - name: Generate report
        working-directory: e2e
        run: npm run report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/cucumber-html-report.html
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
