spring.application.name=tax-service
spring.profiles.active=oracle

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=money_keeper
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.default_schema=CORE
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/oracle
spring.flyway.baselineOnMigrate=true
spring.flyway.schemas=CORE

# Server Configuration
server.port=8082
server.servlet.context-path=/api

# Application Name
spring.application.name=tax-service

# Logging
logging.level.root=INFO
logging.level.com.personal.money.management.tax=DEBUG

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
