spring.application.name=api-gateway
spring.cloud.gateway.default-filters[0].name=RequestRateLimiter
spring.cloud.gateway.default-filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.default-filters[0].args.redis-rate-limiter.burstCapacity=20

# Server Configuration
server.port=8081
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.com.personal.money.management.gateway=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
