spring.profiles.active=local

server.port=8080

# Enable H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.properties.hibernate.default_schema=CORE

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970