name: Backend Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory before build
        run: pwd
      - name: List files in working directory before build
        run: ls -la

      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: ./backend

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: mvn test -Psmall-test
        working-directory: ./backend
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: backend/target/surefire-reports/

      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        continue-on-error: true
        with:
          name: Unit Tests
          path: backend/target/surefire-reports/*.xml
          reporter: junitxml
          fail-on-error: true

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run integration tests
        run: mvn test -Pmedium-test
        working-directory: ./backend
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: backend/target/surefire-reports/

      - name: Publish Integration Test Results
        uses: dorny/test-reporter@v1
        if: always()
        continue-on-error: true
        with:
          name: Integration Tests
          path: backend/target/surefire-reports/*.xml
          reporter: junitxml
          fail-on-error: true
