name: Backend Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Print working directory before build
        run: pwd
      - name: List files in working directory before build
        run: ls -la

      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: ./backend

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        run: mvn clean test -Psmall-test
        working-directory: ./backend
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-small
          path: backend/target/small-test-reports/

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run integration tests
        run: mvn clean verify -Pmedium-test -DskipUnitTests=true
        working-directory: ./backend
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-medium
          path: backend/target/medium-test-reports/

  coverage:
    name: Generate and Upload Code Coverage Report
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    needs: [unit-test, integration-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run coverage report
        run: mvn jacoco:report
        working-directory: ./backend

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/target/site/jacoco/
