name: Build Image Common

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string

jobs:
  common-steps:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ inputs.REGISTRY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
