name: Build Migration Image

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

jobs:
  build-migration-image:
    name: Build and Push Migration Image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ inputs.REGISTRY }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build migration image
        run: |
          docker build -f backend/Dockerfile.migration -t $REGISTRY/money-keeper-migration:$IMAGE_TAG backend
          docker push $REGISTRY/money-keeper-migration:$IMAGE_TAG
