name: Build Migration Image

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

jobs:
  common-steps:
    uses: ./.github/workflows/build-image-common.yml
    with:
      REGISTRY: ${{ inputs.REGISTRY }}

  build-migration-image:
    name: Build and Push Migration Image
    runs-on: ubuntu-latest
    needs: common-steps
    env:
      REGISTRY: ${{ inputs.REGISTRY }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    steps:
      - name: Build migration image
        run: |
          docker build -f backend/Dockerfile.migration -t $REGISTRY/money-keeper-migration:$IMAGE_TAG backend
          docker push $REGISTRY/money-keeper-migration:$IMAGE_TAG
