name: Build All Images

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-migration:
    uses: ./.github/workflows/build-migration-image.yml
    with:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

  build-backend:
    uses: ./.github/workflows/build-backend-image.yml
    with:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

  build-frontend:
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

  debug-notify:
    needs:
      - build-migration
      - build-backend
      - build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Debug Build All Images completion
        run: echo "Build All Images workflow completed successfully"

  call-e2e-test:
    needs: debug-notify
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit

  call-integration-test:
    needs: debug-notify
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
