name: Aggregation Workflow

on:
  workflow_run:
    workflows:
      - unit-test.yml
      - integration-test.yml
      - e2e-test.yml
    types:
      - completed

jobs:
  check-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check all workflows succeeded
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = ['unit-test.yml', 'integration-test.yml', 'e2e-test.yml'];
            for (const workflow of workflows) {
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow,
                branch: context.ref.replace('refs/heads/', ''),
                status: 'completed',
                per_page: 1
              });
              if (runs.data.workflow_runs.length === 0) {
                throw new Error(`No runs found for ${workflow}`);
              }
              const conclusion = runs.data.workflow_runs[0].conclusion;
              if (conclusion !== 'success') {
                throw new Error(`${workflow} did not succeed: ${conclusion}`);
              }
            }
