name: E2E Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-images:
    name: Build Backend and Frontend Docker Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'temurin'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: |
          cd backend
          mvn clean package -DskipTests
          docker build -t $REGISTRY/money-keeper-backend:$IMAGE_TAG .
          docker push $REGISTRY/money-keeper-backend:$IMAGE_TAG

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t $REGISTRY/money-keeper-frontend:$IMAGE_TAG .
          docker push $REGISTRY/money-keeper-frontend:$IMAGE_TAG

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: build-images
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    env:
      SPRING_PROFILES_ACTIVE: ci
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        ports:
          - 1521:1521
        options: >-
          -e ORACLE_PASSWORD=oracle123
          --health-cmd "bash -c 'echo select 1 from dual | sqlplus -s system/oracle123@localhost:1521/XEPDB1 | grep -q 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30
      frontend:
        image: ghcr.io/${{ github.repository_owner }}/money-keeper-frontend:${{ github.sha }}
        ports:
          - 5173:5173
        options: >-
          --health-cmd "curl -f http://localhost:5173 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Oracle to be healthy
        run: |
          for i in {1..30}; do
            echo "Checking Oracle port 1521..."
            if nc -z localhost 1521; then
              echo "Oracle port is open"
              exit 0
            fi
            echo "Oracle port not open yet. Waiting 10 seconds..."
            sleep 10
          done
          exit 1

      - name: Run backend container
        run: |
          docker run -d --name backend -p 8080:8080 \
          -e SPRING_PROFILES_ACTIVE=ci \
          --network host \
          ghcr.io/${{ github.repository_owner }}/money-keeper-backend:${{ github.sha }}

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'
