name: E2E Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'zulu'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build backend
        run: mvn clean install -DskipTests
        working-directory: ./backend
        env:
          JAVA_HOME: /usr/lib/jvm/java-18-temurin

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Start backend and frontend
        run: |
          mvn spring-boot:run -DskipTests -f backend/pom.xml &
          npm start --prefix frontend &
          # Wait for backend to be ready
          for i in {1..30}; do
            if curl -sf http://localhost:8080/actuator/health; then
              echo "Backend is up!"
              break
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          # Wait for frontend to be ready
          for i in {1..30}; do
            if curl -sf http://localhost:5173; then
              echo "Frontend is up!"
              break
            fi
            echo "Waiting for frontend..."
            sleep 5
          done
        shell: bash

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Stop backend and frontend
        run: |
          pkill -f 'mvn spring-boot:run'
          pkill -f 'npm start'
        shell: bash

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'
