name: E2E Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Print working directory before build
        run: pwd
      - name: List files in working directory before build
        run: ls -la

      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: ./backend

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'zulu'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Start frontend
        run: npm start &
        working-directory: ./frontend

      - name: Start backend
        run: mvn spring-boot:run -DskipTests
        working-directory: ./backend

      - name: Verify backend status
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:8080/actuator/health; then
              echo "Backend is up!"
              break
            fi
            echo "Backend not up yet. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Verify frontend status
        run: |
          for i in {1..30}; do
            if curl -sf http://localhost:5173; then
              echo "Frontend is up!"
              break
            fi
            echo "Frontend not up yet. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps    
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'
