name: playwright-code-gen Tests

on:
  workflow_call:
  workflow_run:
    workflows: ["eslint-wrapper"]
    types:
      - completed
    branches:
      - develop
  push:
    branches:
      - develop
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'playwright-code-gen/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  playwright-code-gen-test:
    name: Run playwright-code-gen Tests
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: ci
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
      VITE_BACKEND_HOST: backend
      ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD_SECRET }}
      E2E_SOURCE_FOLDER: playwright-code-gen
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || github.ref }}

      - name: Start Oracle service
        run: ORACLE_PASSWORD=${{ secrets.ORACLE_PASSWORD_SECRET }} docker compose up -d oracle

      - name: Run Flyway migration
        run: bash scripts/flyway_migrate.sh ${{ secrets.ORACLE_PASSWORD_SECRET }}
        env:
          SPRING_DATASOURCE_URL: jdbc:oracle:thin:@localhost:1522/XEPDB1
          
      - name: Start Backend and Frontend containers
        run: docker compose up -d backend frontend

      - name: Wait for Backend to be healthy
        run: bash scripts/wait_for_backend.sh

      - name: Wait for Frontend to be healthy
        run: bash scripts/wait_for_frontend.sh

      - name: Run playwright-code-gen tests
        run: docker compose run --rm -e GITHUB_REF=${{ github.event.workflow_run.head_branch || github.event.pull_request.head.ref || github.ref }} -e GITHUB_SHA=${{ github.event.workflow_run.head_sha || github.event.pull_request.head.sha || github.sha }} -e GITHUB_REPOSITORY=${{ github.repository }} -e BASE_URL=http://frontend:5173 -e API_BASE_URL=http://backend:8080/api playwright-code-gen npm run test:ci

      - name: Generate Allure report
        if: always()
        run: bash scripts/generate_allure_report.sh ${{ env.E2E_SOURCE_FOLDER }}

      - name: Upload Allure report for Github Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ env.E2E_SOURCE_FOLDER }}/test-results/allure-report'
          name: github-pages
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Clean up containers to free resources
      - name: Stop containers
        if: always()
        run: docker compose down
