name: E2E Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    env:
      SPRING_PROFILES_ACTIVE: ci
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
      VITE_BACKEND_HOST: backend
    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD_SECRET }}
        options: >-
          --health-cmd "bash -c 'echo select 1 from dual | sqlplus -s system/$ORACLE_PASSWORD@localhost:1521/XEPDB1 | grep -q 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30
      migration:
        image: ghcr.io/${{ github.repository_owner }}/money-keeper-migration:${{ github.sha }}
        env:
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD_SECRET }}
        options: >-
          --health-cmd "bash -c 'exit 0'"
      backend:
        image: ghcr.io/${{ github.repository_owner }}/money-keeper-backend-image:${{ github.sha }}
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/actuator/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          SPRING_PROFILES_ACTIVE: ci
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD_SECRET }}
      frontend:
        image: ghcr.io/${{ github.repository_owner }}/money-keeper-frontend-image:${{ github.sha }}
        ports:
          - 5173:5173
        options: >-
          --health-cmd "curl -f http://localhost:5173 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e
        
      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        if: always()
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports'
          name: pages

  deploy-report:
    name: Deploy E2E Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: e2e-test
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: pages

      - name: List contents of publish directory for debugging
        run: ls -la ./ || echo "Directory not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports

      - name: Print GitHub Pages URL
        run: |
          echo "GitHub Pages deployed at: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/cucumber-html-report/"
