name: E2E Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  backend-service:
    name: Backend Service
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
      options: --mount type=volume,source=maven-repo,target=/root/.m2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: ./backend

      - name: Start backend service
        run: mvn spring-boot:run -DskipTests
        working-directory: ./backend

  frontend-service:
    name: Frontend Service
    runs-on: ubuntu-latest
    needs: backend-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Start frontend service
        run: npm start
        working-directory: ./frontend

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: [backend-service, frontend-service]
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'
