name: E2E Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-images:
    name: Build Backend and Frontend Docker Images
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-openjdk-18
    env:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: |
          cd backend
          mvn clean package -DskipTests
          docker build -t $REGISTRY/money-keeper-backend:$IMAGE_TAG .
          docker push $REGISTRY/money-keeper-backend:$IMAGE_TAG

      - name: Build frontend image
        run: |
          cd frontend
          docker build -t $REGISTRY/money-keeper-frontend:$IMAGE_TAG .
          docker push $REGISTRY/money-keeper-frontend:$IMAGE_TAG

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: build-images
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    env:
      SPRING_PROFILES_ACTIVE: ci
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}
    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        ports:
          - 1521:1521
        options: >-
          -e ORACLE_PASSWORD=oracle123
          --health-cmd "bash -c 'echo select 1 from dual | sqlplus -s system/oracle123@localhost:1521/XEPDB1 | grep -q 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30
      backend:
        image: ${{ env.REGISTRY }}/money-keeper-backend:${{ env.IMAGE_TAG }}
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/actuator/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          SPRING_PROFILES_ACTIVE: ci
      frontend:
        image: ${{ env.REGISTRY }}/money-keeper-frontend:${{ env.IMAGE_TAG }}
        ports:
          - 5173:5173
        options: >-
          --health-cmd "curl -f http://localhost:5173 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install e2e dependencies
        run: npm install
        working-directory: ./e2e

      - name: Create .env file
        run: cp .env.example .env
        working-directory: ./e2e

      - name: Install Playwright Browsers
        run: npx playwright install-deps
        working-directory: ./e2e

      - name: Run e2e tests
        run: npm run test:parallel
        working-directory: ./e2e

      - name: Generate report
        run: npm run report
        working-directory: ./e2e

      - name: Upload report for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'e2e/reports/cucumber-html-report.html'
