name: eslint-wrapper

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Node.js version
        required: false
        default: '20'
        type: string
      working-directory:
        description: Directory containing package.json
        required: false
        default: frontend
        type: string
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      working-directory:
        required: false
        type: string
        default: frontend

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}-eslint
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  eslint-check:
    name: ESLint
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute lint check
        uses: ./.github/actions/run-eslint
        with:
          node-version: ${{ inputs['node-version'] || '20' }}
          working-directory: ${{ inputs['working-directory'] || 'frontend' }}
