name: Integration Tests

on:
  workflow_run:
    workflows:
      - build.yml
    types:
      - completed

jobs:
  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:latest
        ports:
          - 1521:1521
        options: >-
          -e ORACLE_PASSWORD=oracle123
          --health-cmd "bash -c 'echo select 1 from dual | sqlplus -s system/oracle123@localhost:1521/XEPDB1 | grep -q 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variable for Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=ci" >> $GITHUB_ENV

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for Oracle to be healthy
        run: |
          for i in {1..30}; do
            echo "Checking Oracle port 1521..."
            if nc -z localhost 1521; then
              echo "Oracle port is open"
              exit 0
            fi
            echo "Oracle port not open yet. Waiting 10 seconds..."
            sleep 10
          done
          exit 1

      - name: Run Flyway migrations
        run: mvn -B -ntp flyway:migrate -Pmedium-test
        working-directory: ./backend

      - name: Run integration tests
        run: mvn clean verify -Pmedium-test -DskipUnitTests=true
        working-directory: ./backend

      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-medium
          path: ./backend/target/medium-test-reports/
