name: Pull Request Quality Gate

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  call-unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  call-e2e-test:
    needs:
      - build-backend
      - build-frontend
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit

  call-integration-test:
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
