name: Pull Request Quality Gate

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  execute-unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  execute-e2e-test:
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit

  execute-integration-test:
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
