name: Pull Request Quality Gate

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-backend:
    uses: ./.github/workflows/build-backend-image.yml
    with:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

  build-frontend:
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

  call-unit-test:
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit

  call-e2e-test:
    needs:
      - build-migration
      - build-backend
      - build-frontend
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit

  call-integration-test:
    needs: build-migration
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
