CREATE TABLE icons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    icon_value VARCHAR(255) NOT NULL
);

INSERT INTO icons (label, icon_value) VALUES
('Grid', 'Grid'),
('Shopping', 'ShoppingCart'),
('Food', 'Food'),
('Transport', 'Van'),
('House', 'House'),
('Bills', 'Document'),
('Entertainment', 'Film'),
('Health', 'FirstAidKit'),
('Education', 'Reading'),
('Salary', 'Money'),
('Investment', 'TrendCharts');
